/**
 * @file types/index.ts
 * @description All shared TypeScript type definitions for the Smart IoT Monitor frontend.
 * Every interface here is designed to exactly mirror the backend API response shapes,
 * Socket.IO event payloads, and internal UI data structures.
 *
 * Keep this file in sync with any backend schema changes.
 */

// ---------------------------------------------------------------------------
// Core Entity Types
// ---------------------------------------------------------------------------

/**
 * Represents a physical IoT device (e.g. an ESP32 node) registered in the system.
 */
export interface Device {
  /** UUID primary key assigned by the database. */
  id: string;
  /** Human-readable device identifier sent in every MQTT/HTTP payload (e.g. "esp32-01"). */
  deviceId: string;
  /** Optional friendly name set by the user. */
  name: string | null;
  /** Current connectivity status derived from the last heartbeat timestamp. */
  status: 'online' | 'offline';
  /** ISO-8601 datetime of the last received message from this device. */
  lastSeenAt: string | null;
  /** Wi-Fi RSSI value in dBm (negative integer). Null if never reported. */
  rssi: number | null;
  /** Free heap memory in bytes as reported by the firmware. */
  freeHeap: number | null;
  /** ISO-8601 datetime when this device was first registered. */
  createdAt: string;
  /** ISO-8601 datetime of the last record update. */
  updatedAt: string;
}

/**
 * A single water flow/volume reading captured by the flow sensor on the device.
 */
export interface WaterReading {
  /** UUID primary key. */
  id: string;
  /** Foreign key linking to the originating device's deviceId field. */
  deviceId: string;
  /** Instantaneous flow rate in litres per minute. */
  flowRateLpm: number;
  /** Cumulative total litres dispensed since the device last reset its counter. */
  totalLitres: number;
  /** ISO-8601 datetime when the reading was captured on the device. */
  timestamp: string;
  /** ISO-8601 datetime when the record was persisted in the database. */
  createdAt: string;
}

/**
 * A single electricity reading captured by the PZEM-004T sensor module.
 */
export interface ElectricityReading {
  /** UUID primary key. */
  id: string;
  /** Foreign key linking to the originating device's deviceId field. */
  deviceId: string;
  /** RMS voltage in Volts. */
  voltage: number;
  /** RMS current in Amperes. */
  current: number;
  /** Instantaneous active power in Watts. */
  power: number;
  /** Cumulative energy consumption in kilowatt-hours since last reset. */
  energyKwh: number;
  /** ISO-8601 datetime when the reading was captured on the device. */
  timestamp: string;
  /** ISO-8601 datetime when the record was persisted in the database. */
  createdAt: string;
}

/**
 * An anomaly event generated by the backend anomaly-detection engine.
 */
export interface Anomaly {
  /** UUID primary key. */
  id: string;
  /** Foreign key referencing the device that produced the anomalous reading. */
  deviceId: string;
  /** Which monitored resource triggered the anomaly. */
  resourceType: 'water' | 'electricity';
  /** Classification of how serious the anomaly is. */
  severity: 'low' | 'medium' | 'high';
  /** Human-readable description of what was detected (e.g. "Flow rate 3× above baseline"). */
  message: string;
  /** The actual sensor value that triggered the anomaly. */
  actualValue: number;
  /** The rolling baseline value used for comparison. */
  baselineValue: number;
  /** The deviation threshold that was crossed to generate this anomaly. */
  threshold: number;
  /** ISO-8601 datetime when this anomaly was marked resolved. Null if still active. */
  resolvedAt: string | null;
  /** ISO-8601 datetime when the anomalous reading was captured. */
  timestamp: string;
  /** ISO-8601 datetime when this anomaly record was created in the database. */
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Water API Response Types
// ---------------------------------------------------------------------------

/**
 * Summary statistics for water consumption aggregated over the current calendar day.
 */
export interface WaterTodaySummary {
  /** The device this summary belongs to. */
  deviceId: string;
  /** Total litres consumed since 00:00 local time today. */
  totalLitresToday: number;
  /** Average flow rate across all readings taken today, in LPM. */
  avgFlowRateLpm: number;
  /** Peak (maximum) flow rate recorded today, in LPM. */
  peakFlowRateLpm: number;
  /** Total number of individual readings recorded today. */
  readingCount: number;
  /** ISO-8601 start-of-day boundary used for the aggregation. */
  periodStart: string;
  /** ISO-8601 end-of-day boundary (or current time if today is ongoing). */
  periodEnd: string;
}

/**
 * Paginated list of water readings returned by the history endpoint.
 */
export interface WaterHistoryResponse {
  /** Array of reading objects ordered by timestamp descending. */
  data: WaterReading[];
  /** Total number of readings matching the query (before pagination). */
  total: number;
  /** Maximum number of results per page requested. */
  limit: number;
  /** Zero-based page offset. */
  offset: number;
}

/**
 * One day's aggregated water usage record, used to build the weekly summary chart.
 */
export interface WaterDailySummary {
  /** Calendar date string in YYYY-MM-DD format. */
  date: string;
  /** Total litres consumed on this calendar day. */
  totalLitres: number;
  /** Average flow rate across all readings on this day, in LPM. */
  avgFlowRateLpm: number;
  /** Peak flow rate on this day, in LPM. */
  peakFlowRateLpm: number;
  /** Number of individual readings taken on this day. */
  readingCount: number;
}

/**
 * Multi-day water usage summary (e.g. past 7 or 30 days).
 */
export interface WaterSummaryResponse {
  /** The device this summary belongs to. */
  deviceId: string;
  /** Number of days included in this summary. */
  days: number;
  /** Per-day breakdown, one entry per calendar day. */
  dailySummaries: WaterDailySummary[];
  /** Grand total litres across all days in the summary period. */
  grandTotalLitres: number;
  /** Average daily consumption in litres. */
  avgDailyLitres: number;
}

// ---------------------------------------------------------------------------
// Electricity API Response Types
// ---------------------------------------------------------------------------

/**
 * Summary statistics for electricity consumption aggregated over the current calendar day.
 */
export interface ElectricityTodaySummary {
  /** The device this summary belongs to. */
  deviceId: string;
  /** Total energy consumed since 00:00 local time today, in kWh. */
  totalEnergyKwhToday: number;
  /** Average power draw across all readings taken today, in Watts. */
  avgPowerW: number;
  /** Peak power draw recorded today, in Watts. */
  peakPowerW: number;
  /** Average voltage across all readings today, in Volts. */
  avgVoltage: number;
  /** Average current across all readings today, in Amperes. */
  avgCurrent: number;
  /** Total number of individual readings recorded today. */
  readingCount: number;
  /** ISO-8601 start-of-day boundary used for the aggregation. */
  periodStart: string;
  /** ISO-8601 end-of-day boundary (or current time if today is ongoing). */
  periodEnd: string;
}

/**
 * Paginated list of electricity readings returned by the history endpoint.
 */
export interface ElectricityHistoryResponse {
  /** Array of reading objects ordered by timestamp descending. */
  data: ElectricityReading[];
  /** Total number of readings matching the query (before pagination). */
  total: number;
  /** Maximum number of results per page requested. */
  limit: number;
  /** Zero-based page offset. */
  offset: number;
}

/**
 * One day's aggregated electricity usage record, used to build the weekly summary chart.
 */
export interface ElectricityDailySummary {
  /** Calendar date string in YYYY-MM-DD format. */
  date: string;
  /** Total energy consumed on this calendar day, in kWh. */
  totalEnergyKwh: number;
  /** Average power draw on this day, in Watts. */
  avgPowerW: number;
  /** Peak power draw on this day, in Watts. */
  peakPowerW: number;
  /** Average voltage on this day, in Volts. */
  avgVoltage: number;
  /** Number of individual readings taken on this day. */
  readingCount: number;
}

/**
 * Multi-day electricity usage summary (e.g. past 7 or 30 days).
 */
export interface ElectricitySummaryResponse {
  /** The device this summary belongs to. */
  deviceId: string;
  /** Number of days included in this summary. */
  days: number;
  /** Per-day breakdown, one entry per calendar day. */
  dailySummaries: ElectricityDailySummary[];
  /** Grand total energy consumed across all days, in kWh. */
  grandTotalEnergyKwh: number;
  /** Average daily energy consumption in kWh. */
  avgDailyEnergyKwh: number;
}

// ---------------------------------------------------------------------------
// Anomaly API Response Types
// ---------------------------------------------------------------------------

/**
 * Paginated list of anomalies returned by the anomaly list endpoint.
 */
export interface AnomalyListResponse {
  /** Array of anomaly objects ordered by timestamp descending. */
  data: Anomaly[];
  /** Total number of anomalies matching the query (before pagination). */
  total: number;
  /** Maximum number of results per page requested. */
  limit: number;
  /** Zero-based page offset. */
  offset: number;
}

// ---------------------------------------------------------------------------
// Health Check
// ---------------------------------------------------------------------------

/**
 * Response shape from the backend GET /health endpoint.
 */
export interface HealthCheckResponse {
  /** Overall service status. */
  status: 'ok' | 'degraded' | 'down';
  /** ISO-8601 datetime of this response. */
  timestamp: string;
  /** Semantic version string of the backend service (e.g. "1.0.0"). */
  version: string;
  /** Individual sub-system statuses. */
  services: {
    /** PostgreSQL database connectivity. */
    database: 'ok' | 'error';
    /** MQTT broker connectivity. */
    mqtt: 'ok' | 'error';
    /** Redis/cache connectivity (if applicable). */
    cache?: 'ok' | 'error';
  };
}

// ---------------------------------------------------------------------------
// Socket.IO Event Payload Types
// ---------------------------------------------------------------------------

/**
 * Payload emitted by the server on the `reading:update` Socket.IO event.
 * Contains the most recent readings for both resources in a single push.
 */
export interface ReadingUpdatePayload {
  /** The deviceId that generated these readings. */
  deviceId: string;
  /** Latest water reading, or null if none yet received. */
  water: WaterReading | null;
  /** Latest electricity reading, or null if none yet received. */
  electricity: ElectricityReading | null;
}

/**
 * Payload emitted by the server on the `device:status` Socket.IO event.
 */
export interface DeviceStatusPayload {
  /** The deviceId whose status changed. */
  deviceId: string;
  /** New connectivity status. */
  status: 'online' | 'offline';
  /** ISO-8601 datetime of the status change. */
  timestamp: string;
  /** Wi-Fi RSSI at the time of the event (if applicable). */
  rssi?: number | null;
  /** Free heap at the time of the event (if applicable). */
  freeHeap?: number | null;
}

// ---------------------------------------------------------------------------
// Chart / UI Utility Types
// ---------------------------------------------------------------------------

/**
 * A single [x, y] data-point used by Recharts or any charting library.
 */
export interface ChartDataPoint {
  /** X-axis label — typically a formatted time string (e.g. "14:30") or date ("Mon"). */
  label: string;
  /** Primary numeric value plotted on the Y axis. */
  value: number;
  /** Optional secondary value (e.g. for multi-line charts). */
  value2?: number;
  /** Raw ISO-8601 timestamp for tooltip display. */
  timestamp?: string;
}

/**
 * Preset time-range identifiers used by the history/chart date-range selector.
 */
export type TimeRange = '1h' | '6h' | '24h' | '7d' | '30d' | 'custom';

/**
 * Standardised error object returned when any API call fails.
 */
export interface ApiError {
  /** Short machine-readable error code (e.g. "DEVICE_NOT_FOUND"). */
  code: string;
  /** Human-readable error message suitable for display in a toast. */
  message: string;
  /** HTTP status code of the failed response. */
  status: number;
  /** Optional validation details for 422 errors. */
  details?: Record<string, string[]>;
}

/**
 * Query parameters accepted by the fetchAnomalies API function.
 */
export interface AnomalyQueryParams {
  /** Filter by deviceId. */
  deviceId?: string;
  /** Filter by resource type. */
  resourceType?: 'water' | 'electricity';
  /** Filter by severity. */
  severity?: 'low' | 'medium' | 'high';
  /** Only return unresolved anomalies when true. */
  unresolvedOnly?: boolean;
  /** Maximum number of results to return. */
  limit?: number;
  /** Zero-based page offset for pagination. */
  offset?: number;
}

/**
 * Query parameters accepted by the history fetch functions.
 */
export interface HistoryQueryParams {
  /** ISO-8601 datetime for the start of the query window. */
  from: string;
  /** ISO-8601 datetime for the end of the query window. */
  to: string;
  /** Maximum number of readings to return (default: 100). */
  limit?: number;
}

/**
 * Generic wrapper for successful paginated API list responses.
 */
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  limit: number;
  offset: number;
}
